version: '3.8'

services:
  peakperf:
    image: peakperf
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:8080
    volumes:
      - .:/app
      - /app/build
      - /app/node_modules